# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c28db9f71bfcaf19979cc6ed3051430191d2c2bfdbf6d26f8b98d0e20e8a1381546a1dd4f0a498558e645be26948e5f8f3dd22cc0b9d9303c106d748bf0a7982

test:
  secret_key_base: a2af70797f30508655bf4453a4d8e216a8dcaf8b1e51cebd78d4e2a8041b07be030e1e48a0726f35bf3c0985834484169c77c4a6607226b4fcbed73ced6eff33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
